### ISSUE TITLE
Could not find the dictionary directory in Bluemix

### ISSUE THREAD

**Issue by Dingyj3178** [kotasuizu/node-red-kuromoji#2]
Hi Kotasuizu san

I'm install this node to bluemix  and I want to use the dictionary from Mecab.
But I can't find the node-red-kuromoji/node_modules/kuromoji/dict in Bluemix Env.

BR,

**Comment by kotasuizu** [comment]
Hi, Dingyj3178 san. Thank you for reporting the issue. 
Bluemix ENV Node-RED changed dependency module processing. The dictionary is not loaded on the assumed path. I fixed this problem. Please use the new version.
